src/Entity/Purchase.php
<?php

namespace App\Entity;

use App\Repository\PurchaseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PurchaseRepository::class)
 */
class Purchase
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $id_stripe;

    

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="user")
     * @ORM\JoinColumn(nullable=false)
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=PurchaseHaveProduct::class, mappedBy="purchase", cascade={"remove"})
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $purchaseCommande;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $carrierName;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $carrierPrice;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $delivery;

    public function __construct()
    {
        $this->purchaseCommande = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getIdStripe(): ?string
    {
        return $this->id_stripe;
    }

    public function setIdStripe(?string $id_stripe): self
    {
        $this->id_stripe = $id_stripe;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|PurchaseHaveProduct[]
     */
    public function getPurchaseCommande(): Collection
    {
        return $this->purchaseCommande;
    }

    public function addPurchaseCommande(PurchaseHaveProduct $purchaseCommande): self
    {
        if (!$this->purchaseCommande->contains($purchaseCommande)) {
            $this->purchaseCommande[] = $purchaseCommande;
            $purchaseCommande->setPurchase($this);
        }

        return $this;
    }

    public function removePurchaseCommande(PurchaseHaveProduct $purchaseCommande): self
    {
        if ($this->purchaseCommande->removeElement($purchaseCommande)) {
            // set the owning side to null (unless already changed)
            if ($purchaseCommande->getPurchase() === $this) {
                $purchaseCommande->setPurchase(null);
            }
        }

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrierName;
    }

    public function setCarrierName(string $carrierName): self
    {
        $this->carrierName = $carrierName;

        return $this;
    }

    public function getCarrierPrice(): ?float
    {
        return $this->carrierPrice;
    }

    public function setCarrierPrice(?float $carrierPrice): self
    {
        $this->carrierPrice = $carrierPrice;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(?string $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }
}

src/Form/PurchaseType.php
<?php

namespace App\Form;

use App\Entity\Adresse;
use App\Entity\Purchase;
use App\Entity\Carrier;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PurchaseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $user = $options['user'];

        $builder
            ->add('adresse',EntityType::class,[
                'label' => false,
                'required' => true,
                'class' => Adresse::class,
                'multiple' =>false,
                'expanded' =>true,
                'choices' => $user->getAdresses()
            ])
            ->add('carrier',EntityType::class,[
                'label' => 'Choissisez votre transporteur',
                'required' => true,
                'class' => Carrier::class,
                'multiple' =>false,
                'expanded' =>true,
                'attr' => [
                    'class' => "radio-btn",
                    'data-action' => "click->hello#calcul",

                ],
                'choice_value' => function (?carrier $carrier) {
                    return $carrier ? $carrier->getPrice()*100 : '';
                },
            ])
            ->add('submit',SubmitType::class,[
                'label'=> 'Valider ma commande',
                'attr'=>[
                    'class' => 'btn btn-success btn-block'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'user' => array()
        ]);
    }
}

src/Controller/PurchaseController.php
<?php

namespace App\Controller;

use App\Entity\Purchase;
use App\Entity\User;
use App\Form\PurchaseType;
use App\Repository\PurchaseRepository;
use App\Service\Cart\CartService;
use App\Service\Purchase\ChartPurchaseService;
use App\Service\Purchase\PurchaseService;
use App\Service\StripeService;
use Stripe\Stripe;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;

class PurchaseController extends AbstractController
{
    #[Route('/purchase', name: 'purchase')]
    public function index(PurchaseService $purchaseService): Response
    {
        $user = $this->getDoctrine()->getRepository(User::class)->findOneBy(['id' => $this->getUser()->getId()]);
        $purchase = $this->getDoctrine()->getRepository(Purchase::class)->findOneBy(['user' => $user, 'status' => 'panier']);
        $purchaseService->checkPurchase($purchase, $user);
        return $this->render('purchase/index.html.twig', [
            'controller_name' => 'PurchaseController',
        ]);
    }



    #[Route('/purchase/history/year', name: 'purchase_historyYear')]
    public function purchaseHistoryYear(ChartBuilderInterface $chartBuilder,PurchaseService $purchaseService, ChartPurchaseService $chartPurchaseService): Response
    {

        $purchase = $this->getDoctrine()->getRepository(Purchase::class)->findBy(['status' => 'complete']);
        $yearChart = $chartPurchaseService->barChartPastYear($chartBuilder, $purchase);
        $superTotal = $purchaseService->totalPurchaseYear($purchase);

        return $this->render('purchase/showYear.html.twig', [
            'controller_name' => 'PurchaseController',
            'chart' => $yearChart,
            'superTotal'=>$superTotal
        ]);
    }

    #[Route('/purchase/history/month', name: 'purchase_historyMonth')]
    public function purchaseHistoryMonth(ChartBuilderInterface $chartBuilder, PurchaseService $purchaseService, ChartPurchaseService $chartPurchaseService): Response
    {

        $purchase = $this->getDoctrine()->getRepository(Purchase::class)->findBy(['status' => 'complete']);
        $monthChart = $chartPurchaseService->barChartPastMonth($chartBuilder, $purchase);
        $superTotal = $purchaseService->totalPurchaseMonth($purchase);

        return $this->render('purchase/showMonth.html.twig', [
            'controller_name' => 'PurchaseController',
            'chart' => $monthChart,
            'superTotal'=>$superTotal
        ]);
    }

    #[Route('/purchase/history/admin', name: 'purchase_history_admin')]
    public function purchaseHistoryAdmin(ChartBuilderInterface $chartBuilder, PurchaseService $purchaseService, CartService $cartService, ChartPurchaseService $chartPurchaseService): Response
    {

        $user = $this->getDoctrine()->getRepository(User::class)->findAll();
        $purchase = $this->getDoctrine()->getRepository(Purchase::class)->findAll();
        $callOnService = $purchaseService->purchaseHistory($purchase, $cartService);
        
        if ($purchase) {
            $mixedChartOnUser = $chartPurchaseService->mixedChartOneUser($chartBuilder, $purchase);
        }
        else {
            return $this->render('purchase/nopurchase.html.twig', [
            ]);
        }

        return $this->render('purchase/show.html.twig', [
            'controller_name' => 'PurchaseController',
            'callOnService' => $callOnService,
            'chartMixed' => $mixedChartOnUser
        ]);
    }

    #[Route('/purchase/history/{id}', name: 'purchase_history')]
    public function purchaseHistory($id, ChartBuilderInterface $chartBuilder, PurchaseService $purchaseService, CartService $cartService, ChartPurchaseService $chartPurchaseService): Response
    {

        $user = $this->getDoctrine()->getRepository(User::class)->findOneBy(['id' => $id]);
        $purchase = $this->getDoctrine()->getRepository(Purchase::class)->findBy(['user' => $user, 'status' => 'complete']);
        $callOnService = $purchaseService->purchaseHistory($purchase, $cartService);
        
        if ($purchase) {
            $mixedChartOnUser = $chartPurchaseService->mixedChartOneUser($chartBuilder, $purchase);
        }
        else {
            return $this->render('purchase/nopurchase.html.twig', [
            ]);
        }

        return $this->render('purchase/show.html.twig', [
            'controller_name' => 'PurchaseController',
            'callOnService' => $callOnService,
            'chartMixed' => $mixedChartOnUser
        ]);
    }

    

    #[Route('/purchase/validate/{id}', name: 'purchase_validator')]
    public function purchaseValidator(

        CartService $cartService,Purchase $purchase, StripeService $stripeService,
        Request $request, UrlGeneratorInterface $generator): Response
    {
        $cart = $cartService->getFullCart($purchase);

        $total = $cartService->getTotal($purchase);


        $form = $this->createForm(PurchaseType::class,null,[
            'user' => $this->getUser()
        ]);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            if($form->getData()['adresse'] === null){
                $this->addFlash('notice', 'Veuillez rentrer une adresse de livraison');
            } else {
                return $this->redirect($stripeService->getArrayResponse($cart, $form, $purchase,$generator, $this->getParameter('secretStripe')));
            }
        }

        return $this->render('purchase/index.html.twig',
            [
                'cart' => $cart,
                'form' => $form->createView(),
                'total' => $total
            ]);


    }

    #[Route('/purchase/success/merci/{id}', name: 'order_success')]
    public function paymentSuccess(Request $request, Purchase $purchase, PurchaseService $purchaseService, StripeService $stripeService)
    {
        if($stripeService->checkSuccess($purchase, $this->getParameter('secretStripe')))
        {
            $purch = $this->getDoctrine()->getManager()->getRepository(Purchase::class)->findOneBy(['user'=>$this->getUser(),"status"=>"panier"]);
            //dd($purch,$this->getUser());
            $purchaseService->checkPurchase($purch,$this->getUser());
            return $this->render('order/success.html.twig',[
               'purchase' => $purchase
            ]);
        }
    }

    #[Route('/purchase/failed/desole/{id}', name: 'order_failed')]
    public function paymentFailed(Purchase $purchase)
    {
        return $this->render('order/failed.html.twig',[
            'purchase' => $purchase
        ]);
    }
}

templates/purchase/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Valider ma commande{% endblock %}

{% block body %}
    <h2>Je passe ma commande</h2>
    Choisissez vos préférences de livraison avant de passer commande.
    <hr>
    {% for message in app.flashes('notice') %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
    <div class="row">
        <div class="col-md-6" data-controller="hello" data-total="{{ (total*100) }}">
            {% set formHtml %}
                {{ form_start(form) }}
                {{ form_label(form.adresse, 'Choisissez votre adresse de livraison') }}
                <a href="{{ path('ajouter_adresse') }}">Ajouter une nouvelle adresse</a>
                {{ form_end(form) }}
            {% endset %}
            {{ formHtml|replace({'[br]' : '<br/>'})|raw }}
        </div>
        <div class="col-md-6">
            <div class="text-center">
                <b>Récap de ma commande</b><br>
            </div>
            <div class="order_summary">
                {%  for item in cart %}
                    <div class="row ">
                        <div class="col-2">
                            <img src="{{ vich_uploader_asset(item.product, 'imageFile') | imagine_filter('my_thumb') }}" alt="{{ item.product.name}}"></div>
                        <div class="col-8 my-auto" >
                            {{ item.product.name }}<br/>
                            {{ item.product.price }}€<br/>
                        </div>
                        <div class="col-2 my-auto">
                            x {{ item.quantity }}
                        </div>
                    </div>

                {% endfor %}
            </div>
            <strong>Sous-Total : </strong> {{ (total)|number_format(2, ',', '.') }} €<br/>
            <strong>Livraison : </strong><br/> <div id="ship"></div>
            <strong>Total : </strong> <div id="tot"></div>

        </div>
    </div>
{% endblock %}

templates/purchase/nopurchase.html.twig
{% extends 'base.html.twig' %}

{% block title %}RetroShop - Commandes{% endblock %}

{% block body %}

  <section class="container_purchase">
      <h1>Aucune commande trouvé pour {{app.user.username}}</h1>
  </section>
  
{% endblock %}

templates/purchase/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}RetroShop - Commandes{% endblock %}

{% block body %}
    <section class="container_commandes">
        <div class="commandes">
        
            <h1>Commandes</h1>
            
            {% for cmds in callOnService %}
                {% if cmds.purchase.status == "panier" %}
                {% else %}
                <div class="comm">
                    <table>
                        <tbody>
                            <tr>
                                <th>Numéro de la commande</th>
                                <td>{{ cmds.purchase.id }}</td>
                            </tr>
                            <tr>
                                <th>Date de la commande</th>
                                <td>{{ cmds.purchase.createdAt ? cmds.purchase.createdAt|date('d-m-Y H:i') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td>{{ cmds.purchase.status }}</td>
                            </tr>
                            <tr>
                                <th>Total</th>
                                <td>{{ cmds.purchase.total }}€</td>
                            </tr>
                            <tr>
                                <th>Référence achat</th>
                                <td>{{ cmds.purchase.idStripe }}</td>
                            </tr>
                            
                        </tbody>
                        
                    </table>

                    {% for pan in cmds.cart %}
                        <div>
                            <p>{{ pan.product.name }}, quantity : {{ pan.quantity  }}, {{pan.product.price}}€/u</p>
                            
                        </div>
                    {% endfor %}
                     
                </div>
                {% endif %} 
            {% endfor %}
        </div>

        <div class="stats">
            {% if is_granted('ROLE_ADMIN') %}
                
                <h1>Stats</h1>
            
                {{ render_chart(chartMixed) }}
            
             
            {% endif %}
        </div>

        {% if is_granted('ROLE_ADMIN') %}
            
            <button><a href="{{path('purchase_historyMonth')}}">Voir les stats du mois</a></button>

            <button><a href="{{path('purchase_historyYear')}}">Voir les stats de l'année</a></button>
            
        {% endif %}
        

    </section>

{% endblock %}

templates/purchase/showMonth.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commandes{% endblock %}

{% block body %}
    
    {% if app.user.roles[1] is defined%}
    {% if app.user.roles[1]%}
    
    {{ render_chart(chart) }}
    
    {% endif %}
    {% endif %}

    <p>Total des ventes sur le mois : {{ superTotal }}</p>

    <button class="mois"><a href="{{path('purchase_history_admin')}}">Revenir à la page commande</a></button>

{% endblock %}

templates/purchase/showYear.html.twig
{% extends 'base.html.twig' %}

{% block title %}RetroShop - Stats de l'année{% endblock %}

{% block body %}
    
    {% if app.user.roles[1] is defined%}
    {% if app.user.roles[1]%}
    
    {{ render_chart(chart) }}
    
    {% endif %}
    {% endif %}

    <p>Total des ventes sur les 12 derniers mois : {{ superTotal }}</p>

    <button class="year"><a href="{{path('purchase_history_admin')}}">Revenir à la page commande</a></button>
{% endblock %}