src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Serializable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface, Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_naissance;


    /**
     * @ORM\OneToMany(targetEntity=Adresse::class, mappedBy="user",  orphanRemoval=true)
     */

    private $adresses;



    /**
     * @ORM\OneToMany(targetEntity=Purchase::class, mappedBy="user", orphanRemoval=true)
     */
    private $user;


    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

  

    public function __construct()
    {
        $this->user = new ArrayCollection();

        $this->adresses = new ArrayCollection();

        $this->comments = new ArrayCollection();
        $this->adresse = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }



    /**
     * @return Collection|Purchase[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(Purchase $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
            $user->setUser($this);
        }

        return $this;
    }

    public function removeUser(Purchase $user): self
    {
        if ($this->user->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getUser() === $this) {
                $user->setUser(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getId();
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }
   
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
        ));
    }

    /**
     * @return Collection|Adresse[]
     */
    public function getAdresses(): Collection
    {
        return $this->adresses;
    }

    public function addAdresse(Adresse $adresse): self
    {
        if (!$this->adresses->contains($adresse)) {
            $this->adresses[] = $adresse;
            $adresse->setUser($this);
        }

        return $this;
    }

    public function removeAdress(Adresse $adresse): self
    {
        if ($this->adresses->removeElement($adresse)) {
            // set the owning side to null (unless already changed)
            if ($adresse->getUser() === $this) {
                $adresse->setUser(null);
            }
        }

        return $this;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function unserialize($data)
    {
        list(
            $this->id,
            $this->username,
            $this->password,
        ) = unserialize($data);
    }

    

}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username',TextType::class,[
                'label'=>'Veuillez choisir un nom d utilisateur',
                'constraints' => new Length([
                    'min' => 2,
                    'max' => 30
                ])
            ])
            ->add('prenom',TextType::class,[
                'label' => 'Veuillez rentrer votre prénom',
                'constraints' => new Length([
                    'min' => 2,
                    'max' => 30
                ]),
            ])
            ->add('nom',TextType::class,[
                'label' => 'Veuillez rentrer votre nom',
                'constraints' => new Length([
                    'min' => 2,
                    'max' => 30
                ]),
            ])
            ->add('email',EmailType::class,[
                'label' => 'Email',
                'constraints' => new Length([
                    'min' => 2,
                    'max' => 60]),
                'attr' =>[
                    'placeholder' => 'Merci de saisir votre adresse email'
                ]
            ])
            ->add('genre', ChoiceType::class,
                array(
                    'label'     => 'Genre',
                    'choices'  =>
                        array(
                            'Homme' => 'Homme',
                            'Femme'  => 'Femme',
                            'Autre'  => 'Autre',
                        ),
                    'expanded' => true,
                    'multiple' => false
                )
            )
            ->add('date_naissance',BirthdayType::class,[
                'label' => 'Date de naissance',
            ])
            ->add('old_password',PasswordType::class,[
                'label' => 'Mon mot de passe actuel',
                'mapped'=>false,
                'attr' =>[
                    'placeholder' => 'Veuillez saisir votre mot de passe actuel'
                ]
            ])
            ->add('new_password',RepeatedType::class,[
                'type' => PasswordType::class,
                'mapped' => false,
                'invalid_message' => 'Les mots de passe et la confirmation doivent etre identiques',
                'label' => 'Mon nouveau mot de passe',
                'required' => true,
                'first_options' => [
                    'label' => "Mon nouveau mot de passe",
                    'attr' => [
                        'placeholder ' => "Merci de saisir votre nouveau mot de passe"
                    ]
                ],
                'second_options' => [
                    'label' => "Confirmez votre mot de passe",
                    'attr' => [
                        'placeholder ' => "Merci de confirmer votre nouveau mot de passe"
                    ]

                ]
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Comments;
use App\Entity\Purchase;
use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Security as CoreSecurity;

#[Route('/user')]
class UserController extends AbstractController
{

    #[Route('/', name: 'user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {

        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),

        ]);
    }

    #[Route('/new', name: 'user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserPasswordHasherInterface $hasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user->setPassword($hasher->hashPassword($user, $form['password']->getData()));
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[
        Route('/show/{id}/admin', name: 'user_show_admin', methods: ['GET', 'POST'])
    ]
    public function show(User $user): Response
    {
        if($this->isGranted('ROLE_ADMIN')){
            return $this->render('user/show.html.twig', [
                'user' => $user,
            ]);
        } else {
            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }
    }

    #[
        Route('/{id}/edit/admin', name: 'user_edit', methods: ['GET', 'POST']),
        Route('/edit', name: 'client_edit', methods: ['GET', 'POST']),
    ]
    public function edit(Request $request, ?User $user,UserPasswordHasherInterface $hasher): Response
    {

        $notification = null;

        if(is_null($user))
        {
            $user = $this->getUser();
        }else{
            if(!$this->isGranted('ROLE_ADMIN')){
                return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
            }
        }

        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $old_password = $form->get('old_password')->getData();

            if($hasher->isPasswordValid($user,$old_password)){
                $new_password = $form->get('new_password')->getData();
                $password = $hasher->hashPassword($user,$new_password);
                $user->setPassword($password);

                $this->getDoctrine()->getManager()->flush();
                $this->addFlash("notice" , "OUI!");


            } else {
                $this->addFlash("notice" , "NON");

            }

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,

        ]);
    }


    #[Route('/{id}', name: 'user_delete', methods: ['POST']),]
    public function delete(Request $request, User $user): Response
    {

        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
            $request->getSession()->invalidate();
            $this->container->get('security.token_storage')->setToken(null);

        }

        return $this->redirectToRoute('accueil_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
{% if is_granted("ROLE_ADMIN") %}
<form method="post" action="{{ path('user_delete_admin', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Supprimer le Compte</button>
</form>
{% else %}
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Supprimer le Compte</button>
</form>

{% endif %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RetroShop - Mon compte{% endblock %}

{% block body %}
<section class="container_user">

    {% if app.user.roles[0] is defined %}

    {% if app.user.roles[0] %}
    <div class="profil_user">
    
        <h1>Profil de {{app.user.username}}</h1>

        <div class="profil">
            <table>
                <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ app.user.id }}</td>
                    </tr>
                    <tr>
                        <th>Username</th>
                        <td>{{ app.user.username }}</td>
                    </tr>
                    <tr>
                        <th>Nom</th>
                        <td>{{ app.user.nom }}</td>
                    </tr>
                    <tr>
                        <th>Prenom</th>
                        <td>{{ app.user.prenom }}</td>
                    </tr>
                    <tr>
                        <th>Genre</th>
                        <td>{{ app.user.genre }}</td>
                    </tr>
                    <tr>
                        <th>Date_naissance</th>
                        <td>{{ app.user.dateNaissance ? app.user.dateNaissance|date('Y-m-d') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Mes adresses</th>
                        <td><a href="{{ path('mes_adresses') }}">Gérer mes adresses</a></td>
                    </tr>
                </tbody>
            </table>
        </div>


        {% for message in app.flashes('notice') %}
            <div class="alert alert-info">{{ message }}</div>
        {% endfor %}


        <button><a href="{{ path('client_edit') }}">Modifier mon profil</a></button>

    </div>
    {% endif %}

    {% endif %}

{% if is_granted("ROLE_ADMIN") %}
   <div class="users">                
        <h1>Tous les Utilisateurs</h1>

            <table>
                <thead>
                    <tr>
                        <th>Pseudo</th>
                        <th>Nom</th>
                        <th>Prenom</th>
                        <th>Genre</th>
                        <th>Date de naissance</th>
                        <th></th>
                    </tr>

                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.nom }}</td>
                        <td>{{ user.prenom }}</td>
                        <td>{{ user.genre }}</td>
                        <td>{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
                        <td>
                            <button><a href="{{ path('user_show_admin', {'id': user.id}) }}">Voir le profil</a></button>
                            <button><a href="{{ path('user_edit', {'id': user.id}) }}">Modifier le profil</a></button>
                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="13">no records found</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        <button><a href="{{ path('user_new') }}">Créer un nouveau utilisateur</a></button>
    {% endif %}
        

</section>            

{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            {# <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr> #}
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Genre</th>
                <td>{{ user.genre }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d H:i:s') : '' }}</td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('purchase_history', {'id': user.id}) }}">historique des commandes</a>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}